# Generated by Django 4.1.1 on 2022-10-26 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyDjApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='userInfo',
        ),
    ]
