# Generated by Django 4.1.1 on 2022-10-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyDjApp', '0002_rename_user_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='userStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('topSongs', models.CharField(max_length=150)),
                ('topArtists', models.CharField(max_length=100)),
                ('dateCaptured', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='userSuggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('posFeedback', models.CharField(max_length=150)),
                ('negFeedback', models.CharField(max_length=100)),
                ('dateCaptured', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='userToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('aceess_token', models.CharField(max_length=150)),
                ('expiration_period', models.CharField(max_length=100)),
                ('refresh_token', models.CharField(max_length=150)),
            ],
        ),
    ]
