# Generated by Django 4.1.1 on 2022-11-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyDjApp', '0003_userstats_usersuggestions_usertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='dateCaptured',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='topArtists',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='topSongs',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='usersuggestions',
            name='dateCaptured',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usersuggestions',
            name='negFeedback',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='usersuggestions',
            name='posFeedback',
            field=models.JSONField(),
        ),
    ]
